spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
h1:
  h2:
    h3: this in {big sliy bear} area
---
spring:
  profiles: test
h1:
  h2:
    h3: this in {very much is not enough *2} area