spring:
  profiles:
    active:
    - dev
---
server:
  port: 11112
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: true
    service-url: #defaultZone集群环境下配置多个服务Eureka节点,以逗号分隔开
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true #访问路径显示ip地址
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
---
server:
  port: 11113
spring:
  profiles: test
eureka:
  client:
    register-with-eureka: true
    service-url: #defaultZone集群环境下配置多个服务Eureka节点,以逗号分隔开
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true #访问路径显示ip地址
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}